# Generated by exp3.sh (look for the journal section)

pdf("ZBS-vs-Lm.pdf", width=15, height=4, family="Times")
par(xpd=NA, mfrow=c(1,3), mar=c(4,4,2.5,0.5), cex=1.1) # margin: bottom left top right

num_FFD <- c(300, 400, 500, 600, 700, 800, 900, 1000)
legend <- c("DVHU (Lm=3)", "DVHU (Lm=6)", "DVHU (Lm=9)", "DSA (Lm=3)", "DSA (Lm=6)", "DSA (Lm=9)")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#       Average latency
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# D2VHU
avg_lat <- c(2.493195, 2.664993, 2.812823, 2.874498, 2.990605, 3.007247,  3.011240,  3.068575)	# Lm=3
plot(num_FFD, avg_lat, type='o', pch=1, ylim=c(0,50),
	xlab='Number of nodes', ylab='Average latency (slots)')

avg_lat <- c(5.368911, 5.881003, 6.354796, 6.664167, 7.019871, 7.346538,  7.647937,  8.004921)	# Lm=6
lines(num_FFD, avg_lat, type='o', pch=2)

avg_lat <- c(7.692557, 8.336266, 8.680566, 9.058133, 9.459860, 9.845405, 10.196879, 10.523902)	# Lm=9
lines(num_FFD, avg_lat, type='o', pch=3)

# DSA
avg_lat <- c( 8.727868,  9.932015, 11.073346, 11.983247, 12.655134, 12.877948, 13.156328, 13.395595)
lines(num_FFD, avg_lat, type='o', pch=4)

avg_lat <- c(19.244618, 23.114092, 25.724555, 29.077456, 31.771083, 33.830581, 36.095046, 38.654935)
lines(num_FFD, avg_lat, type='o', pch=5)

avg_lat <- c(26.581479, 30.800467, 33.546104, 37.435100, 40.314578, 42.654919, 45.556563, 48.478629)
lines(num_FFD, avg_lat, type='o', pch=6)

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#       Fraction of associated devices
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# D2VHU
num_assoc <- c( 40.40,  53.63,  64.97,  73.73,  83.88,  92.37,  95.69, 103.45)
num_assoc <- num_assoc / num_FFD
plot(num_FFD, num_assoc, type='o', pch=1, ylim=c(0,1),
	xlab='Number of nodes', ylab='Fraction of associated nodes')

num_assoc <- c(131.22, 195.11, 254.23, 309.86, 369.20, 430.01, 489.81, 559.63)
num_assoc <- num_assoc / num_FFD
lines(num_FFD, num_assoc, type='o', pch=2)

num_assoc <- c(252.94, 357.43, 452.72, 555.17, 648.84, 742.79, 838.56, 934.22)
num_assoc <- num_assoc / num_FFD
lines(num_FFD, num_assoc, type='o', pch=3)

# DSA
num_assoc <- c( 50.42,  70.27,  90.54, 108.16, 127.62, 145.11, 163.81,  179.65)
num_assoc <- num_assoc / num_FFD
lines(num_FFD, num_assoc, type='o', pch=4)

num_assoc <- c(179.30, 269.08, 357.96, 442.68, 530.93, 616.38, 705.89,  787.51)
num_assoc <- num_assoc / num_FFD
lines(num_FFD, num_assoc, type='o', pch=5)

num_assoc <- c(294.88, 399.34, 499.97, 599.99, 700.00, 800.00, 900.00, 1000.00)
num_assoc <- num_assoc / num_FFD
lines(num_FFD, num_assoc, type='o', pch=6)

legend(-200, 1.25, legend=legend, pch=seq(1,length(legend)), ncol=length(legend))

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#       Ratio of unaccommodated devices
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# D2VHU
num_assoc <- c(0.967308, 0.941123, 0.942801, 0.929823, 0.940715, 0.922170, 0.913135, 0.924056)
plot(num_FFD, num_assoc, type='o', pch=1, ylim=c(0.9,1.0),
	xlab='Number of nodes', ylab='Ratio of unaccommodated nodes')

num_assoc <- c(0.985366, 0.970804, 0.956408, 0.945488, 0.937907, 0.949224, 0.940550, 0.922860)
lines(num_FFD, num_assoc, type='o', pch=2)

num_assoc <- c(0.990366, 0.992193, 0.981701, 0.987459, 0.985740, 0.978571, 0.986086, 0.979292)
lines(num_FFD, num_assoc, type='o', pch=3)

# not applicable to DSA

dev.off()
